# Generated by Django 2.2.24 on 2022-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Telegram ID юзера')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('phonenumber', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
        ),
    ]
