# Generated by Django 2.2.24 on 2022-10-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplan.Dish'),
        ),
    ]
