# Generated by Django 2.2.24 on 2022-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0003_auto_20221006_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingridients',
            name='product',
        ),
        migrations.AddField(
            model_name='ingridients',
            name='products',
            field=models.TextField(blank=True, null=True),
        ),
    ]
