# Generated by Django 4.1.2 on 2022-10-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0004_auto_20221006_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridients',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='dishtype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='DishType',
        ),
        migrations.DeleteModel(
            name='Ingridients',
        ),
    ]
